### ISSUE TITLE
您好，wo

### ISSUE THREAD

**Issue by Caius1L** [yuyufeng1994/KnowledgeLibrary#4]
关于red5流媒体的搭建我想向您请教一些问题，想问问您当初怎么整合red5的

**Comment by Caius1L** [comment]
这个项目是需要引入的时候就将他设置为red5项目吗？我将您的项目导入后所有功能都可以的实现，但是视频预览一直不成功，red5我也下了，可以成功运行它的demo，但是不知道怎么整合进项目，请问您当初是怎么整合配置red5的，谢谢了。

**Comment by yuyufeng1994** [comment]
先去单独学习下 red5的搭建吧，不是很难的
